# Generated by Django 5.0.6 on 2024-06-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100, null=True)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('aro', models.IntegerField()),
                ('color', models.CharField(max_length=100, null=True)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='img')),
            ],
        ),
    ]
