# Generated by Django 5.0.6 on 2024-06-27 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accesorios',
        ),
        migrations.DeleteModel(
            name='Bicicleta',
        ),
    ]
