# Generated by Django 4.2.13 on 2024-06-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_bicicleta_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('modelo', models.CharField(max_length=100)),
                ('aro', models.IntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=300)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('valor_cotizado', models.IntegerField()),
                ('valor_repuestos', models.IntegerField()),
                ('valor_final', models.IntegerField()),
                ('metodo_pago', models.CharField(choices=[('1', 'Efectivo'), ('2', 'Debito'), ('3', 'Credito')], max_length=1)),
                ('ingreso', models.DateField()),
                ('estado', models.IntegerField()),
                ('comentarios', models.CharField(max_length=300)),
                ('finalizado', models.DateField()),
            ],
        ),
    ]
