# Generated by Django 4.2.13 on 2024-06-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
