# Generated by Django 4.2.13 on 2024-06-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_cliente_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('1', 'Ingresado'), ('2', 'En Proceso'), ('3', 'Finalizado'), ('4', 'Entregado')], max_length=1),
        ),
    ]
