# Generated by Django 4.2.13 on 2024-06-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_servicio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='finalizado',
            field=models.DateField(null=True),
        ),
    ]
