# Generated by Django 5.0.6 on 2024-06-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_accesorios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accesorios',
            new_name='Accesorio',
        ),
    ]
