# Generated by Django 4.2.13 on 2024-06-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_servicio_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='cod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente'),
        ),
    ]
