# Generated by Django 4.2.13 on 2024-07-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Bicicleta'), ('2', 'Casco'), ('3', 'Guantes')], max_length=2)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('aro', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='img')),
            ],
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='bicicleta',
            new_name='Producto',
        ),
    ]
