# Generated by Django 4.2.13 on 2024-07-03 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_accesorios_accesorio'),
        ('home', '0013_producto_rename_bicicleta_venta_producto'),
    ]

    operations = [
    ]
