# Generated by Django 4.2.13 on 2024-07-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_producto_color_remove_producto_imagen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accesorio',
        ),
    ]
