# Generated by Django 4.2.13 on 2024-07-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_accesorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_producto',
            field=models.CharField(choices=[('1', 'Bicicleta'), ('2', 'Casco'), ('3', 'Guantes')], default='default_value', max_length=2),
            preserve_default=False,
        ),
    ]
